# Generated by Django 4.1.7 on 2023-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='web/images/')),
                ('new_price', models.IntegerField(blank=True, default=0, null=True)),
                ('old_price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
